# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b2c4a8900c79635d5737d84946824dd1a16a9d3a3ee680899aa8d5971da90c85038639f6c488dcd921cbcd82e54c435e9faea9252cff63932fa5595601aed08

test:
  secret_key_base: a49b75e51bd8715805055f5194bb8d91f878d9579495b2c0edbb9b1906d102c47f51cc47f8111fbfcac5df4062ad3c1f491b1079b88573d6b43e4ce0b73af403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
